on:
  push:
    branches: [ devarpit ]
  pull_request:
    branches: [ devarpit ]

permissions:
  contents: read

jobs:
  build:

    steps:
    - uses: actions/checkout@v3

      with:
        path: htdocs
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
